name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-readme-with-parravidales-blog:
    name: Update this repo's README with the latest parravidales blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://blog.parravidales.es/rss"
